//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimosWebApp.TimosWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TimosUri/", ConfigurationName="TimosWebService.TimosActionServiceSoap")]
    public interface TimosActionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet GetActions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/StartSimpleAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string StartSimpleAction(int nIdAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/StartAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string StartAction(int nIdAction, string[] strParametres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActionTableName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetActionTableName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActionIdFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetActionIdFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActionLabelFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetActionLabelFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActionDescpritionFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetActionDescpritionFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetActionTypeFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetActionTypeFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetVariablesTableNameName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetVariablesTableNameName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetVariableIdFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetVariableIdFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetVariableNameFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetVariableNameFieldName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TimosUri/GetVariableTypeFieldName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetVariableTypeFieldName();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimosActionServiceSoapChannel : TimosWebApp.TimosWebService.TimosActionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimosActionServiceSoapClient : System.ServiceModel.ClientBase<TimosWebApp.TimosWebService.TimosActionServiceSoap>, TimosWebApp.TimosWebService.TimosActionServiceSoap {
        
        public TimosActionServiceSoapClient() {
        }
        
        public TimosActionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimosActionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimosActionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimosActionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Data.DataSet GetActions() {
            return base.Channel.GetActions();
        }
        
        public string StartSimpleAction(int nIdAction) {
            return base.Channel.StartSimpleAction(nIdAction);
        }
        
        public string StartAction(int nIdAction, string[] strParametres) {
            return base.Channel.StartAction(nIdAction, strParametres);
        }
        
        public string GetActionTableName() {
            return base.Channel.GetActionTableName();
        }
        
        public string GetActionIdFieldName() {
            return base.Channel.GetActionIdFieldName();
        }
        
        public string GetActionLabelFieldName() {
            return base.Channel.GetActionLabelFieldName();
        }
        
        public string GetActionDescpritionFieldName() {
            return base.Channel.GetActionDescpritionFieldName();
        }
        
        public string GetActionTypeFieldName() {
            return base.Channel.GetActionTypeFieldName();
        }
        
        public string GetVariablesTableNameName() {
            return base.Channel.GetVariablesTableNameName();
        }
        
        public string GetVariableIdFieldName() {
            return base.Channel.GetVariableIdFieldName();
        }
        
        public string GetVariableNameFieldName() {
            return base.Channel.GetVariableNameFieldName();
        }
        
        public string GetVariableTypeFieldName() {
            return base.Channel.GetVariableTypeFieldName();
        }
    }
}
