//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timos.acteurs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CFormEditionActeur {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CFormEditionActeur() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("timos.acteurs.CFormEditionActeur", typeof(CFormEditionActeur).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ArrayList.
        /// </summary>
        public static System.Collections.ArrayList glColumn1_ActiveControlItems {
            get {
                object obj = ResourceManager.GetObject("glColumn1.ActiveControlItems", resourceCulture);
                return ((System.Collections.ArrayList)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ArrayList.
        /// </summary>
        public static System.Collections.ArrayList glColumn2_ActiveControlItems {
            get {
                object obj = ResourceManager.GetObject("glColumn2.ActiveControlItems", resourceCulture);
                return ((System.Collections.ArrayList)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ArrayList.
        /// </summary>
        public static System.Collections.ArrayList glColumn3_ActiveControlItems {
            get {
                object obj = ResourceManager.GetObject("glColumn3.ActiveControlItems", resourceCulture);
                return ((System.Collections.ArrayList)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ArrayList.
        /// </summary>
        public static System.Collections.ArrayList glColumn4_ActiveControlItems {
            get {
                object obj = ResourceManager.GetObject("glColumn4.ActiveControlItems", resourceCulture);
                return ((System.Collections.ArrayList)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=702,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_extLinkField_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_extLinkField.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=310,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_extModulesAssociator_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_extModulesAssociator.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=353,Y=56}.
        /// </summary>
        public static System.Drawing.Point m_extStyle_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_extStyle.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=497,Y=17}.
        /// </summary>
        public static System.Drawing.Point m_gestionnaireModeEdition_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_gestionnaireModeEdition.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ObjectModel.ReadOnlyCollection`1[sc2i.formulaire.CAffectationsProprietes].
        /// </summary>
        public static System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes> m_panelContacts_AffectationsPourNouveauxElements {
            get {
                object obj = ResourceManager.GetObject("m_panelContacts.AffectationsPourNouveauxElements", resourceCulture);
                return ((System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes>)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ObjectModel.ReadOnlyCollection`1[sc2i.formulaire.CAffectationsProprietes].
        /// </summary>
        public static System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes> m_panelListeRessourcesDetenues_AffectationsPourNouveauxElements {
            get {
                object obj = ResourceManager.GetObject("m_panelListeRessourcesDetenues.AffectationsPourNouveauxElements", resourceCulture);
                return ((System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes>)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=463,Y=56}.
        /// </summary>
        public static System.Drawing.Point m_timer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_timer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=559,Y=56}.
        /// </summary>
        public static System.Drawing.Point m_toolTip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("m_toolTip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Collections.ObjectModel.ReadOnlyCollection`1[sc2i.formulaire.CAffectationsProprietes].
        /// </summary>
        public static System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes> m_wndListeEquipements_AffectationsPourNouveauxElements {
            get {
                object obj = ResourceManager.GetObject("m_wndListeEquipements.AffectationsPourNouveauxElements", resourceCulture);
                return ((System.Collections.ObjectModel.ReadOnlyCollection<sc2i.formulaire.CAffectationsProprietes>)(obj));
            }
        }
    }
}
