//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4927
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace TestServicWebWSDL.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="request_serv_change", Namespace="http://schemas.hp.com/SM/7")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArrayType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructureType))]
    public partial class request_serv_change : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Retrieverequest_changeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Retrieverequest_changeKeysListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Retrieverequest_changeListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public request_serv_change() {
            this.Url = global::TestServicWebWSDL.Properties.Settings.Default.TestServicWebWSDL_WebReference_request_serv_change;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Retrieverequest_changeCompletedEventHandler Retrieverequest_changeCompleted;
        
        /// <remarks/>
        public event Retrieverequest_changeKeysListCompletedEventHandler Retrieverequest_changeKeysListCompleted;
        
        /// <remarks/>
        public event Retrieverequest_changeListCompletedEventHandler Retrieverequest_changeListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Retrieve", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Retrieverequest_changeResponse", Namespace="http://schemas.hp.com/SM/7")]
        public Retrieverequest_changeResponse Retrieverequest_change([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] Retrieverequest_changeRequest Retrieverequest_changeRequest) {
            object[] results = this.Invoke("Retrieverequest_change", new object[] {
                        Retrieverequest_changeRequest});
            return ((Retrieverequest_changeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Retrieverequest_changeAsync(Retrieverequest_changeRequest Retrieverequest_changeRequest) {
            this.Retrieverequest_changeAsync(Retrieverequest_changeRequest, null);
        }
        
        /// <remarks/>
        public void Retrieverequest_changeAsync(Retrieverequest_changeRequest Retrieverequest_changeRequest, object userState) {
            if ((this.Retrieverequest_changeOperationCompleted == null)) {
                this.Retrieverequest_changeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieverequest_changeOperationCompleted);
            }
            this.InvokeAsync("Retrieverequest_change", new object[] {
                        Retrieverequest_changeRequest}, this.Retrieverequest_changeOperationCompleted, userState);
        }
        
        private void OnRetrieverequest_changeOperationCompleted(object arg) {
            if ((this.Retrieverequest_changeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Retrieverequest_changeCompleted(this, new Retrieverequest_changeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RetrieveKeysList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Retrieverequest_changeKeysListResponse", Namespace="http://schemas.hp.com/SM/7")]
        public Retrieverequest_changeKeysListResponse Retrieverequest_changeKeysList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] Retrieverequest_changeKeysListRequest Retrieverequest_changeKeysListRequest) {
            object[] results = this.Invoke("Retrieverequest_changeKeysList", new object[] {
                        Retrieverequest_changeKeysListRequest});
            return ((Retrieverequest_changeKeysListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Retrieverequest_changeKeysListAsync(Retrieverequest_changeKeysListRequest Retrieverequest_changeKeysListRequest) {
            this.Retrieverequest_changeKeysListAsync(Retrieverequest_changeKeysListRequest, null);
        }
        
        /// <remarks/>
        public void Retrieverequest_changeKeysListAsync(Retrieverequest_changeKeysListRequest Retrieverequest_changeKeysListRequest, object userState) {
            if ((this.Retrieverequest_changeKeysListOperationCompleted == null)) {
                this.Retrieverequest_changeKeysListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieverequest_changeKeysListOperationCompleted);
            }
            this.InvokeAsync("Retrieverequest_changeKeysList", new object[] {
                        Retrieverequest_changeKeysListRequest}, this.Retrieverequest_changeKeysListOperationCompleted, userState);
        }
        
        private void OnRetrieverequest_changeKeysListOperationCompleted(object arg) {
            if ((this.Retrieverequest_changeKeysListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Retrieverequest_changeKeysListCompleted(this, new Retrieverequest_changeKeysListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RetrieveList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Retrieverequest_changeListResponse", Namespace="http://schemas.hp.com/SM/7")]
        public Retrieverequest_changeListResponse Retrieverequest_changeList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.hp.com/SM/7")] Retrieverequest_changeListRequest Retrieverequest_changeListRequest) {
            object[] results = this.Invoke("Retrieverequest_changeList", new object[] {
                        Retrieverequest_changeListRequest});
            return ((Retrieverequest_changeListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Retrieverequest_changeListAsync(Retrieverequest_changeListRequest Retrieverequest_changeListRequest) {
            this.Retrieverequest_changeListAsync(Retrieverequest_changeListRequest, null);
        }
        
        /// <remarks/>
        public void Retrieverequest_changeListAsync(Retrieverequest_changeListRequest Retrieverequest_changeListRequest, object userState) {
            if ((this.Retrieverequest_changeListOperationCompleted == null)) {
                this.Retrieverequest_changeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieverequest_changeListOperationCompleted);
            }
            this.InvokeAsync("Retrieverequest_changeList", new object[] {
                        Retrieverequest_changeListRequest}, this.Retrieverequest_changeListOperationCompleted, userState);
        }
        
        private void OnRetrieverequest_changeListOperationCompleted(object arg) {
            if ((this.Retrieverequest_changeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Retrieverequest_changeListCompleted(this, new Retrieverequest_changeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeRequest {
        
        private request_changeModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public Retrieverequest_changeRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        public request_changeModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeModelType {
        
        private request_changeKeysType keysField;
        
        private request_changeInstanceType instanceField;
        
        private MessageType[] messagesField;
        
        private string queryField;
        
        /// <remarks/>
        public request_changeKeysType keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        public request_changeInstanceType instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeKeysType {
        
        private StringType changeNumberField;
        
        private string queryField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class StringType {
        
        private string typeField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool readonlyField;
        
        private bool readonlyFieldSpecified;
        
        private string valueField;
        
        public StringType() {
            this.typeField = "String";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readonlySpecified {
            get {
                return this.readonlyFieldSpecified;
            }
            set {
                this.readonlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class AttachmentType {
        
        private string contentTypeField;
        
        private string hrefField;
        
        private string contentIdField;
        
        private string actionField;
        
        private string nameField;
        
        private string typeField;
        
        private int lenField;
        
        private bool lenFieldSpecified;
        
        private string charsetField;
        
        private string attachmentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/2005/05/xmlmime")]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int len {
            get {
                return this.lenField;
            }
            set {
                this.lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lenSpecified {
            get {
                return this.lenFieldSpecified;
            }
            set {
                this.lenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class DecimalType {
        
        private string typeField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool readonlyField;
        
        private bool readonlyFieldSpecified;
        
        private decimal valueField;
        
        public DecimalType() {
            this.typeField = "Decimal";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readonlySpecified {
            get {
                return this.readonlyFieldSpecified;
            }
            set {
                this.readonlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class ArrayType {
        
        private string typeField;
        
        public ArrayType() {
            this.typeField = "Array";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class DateTimeType {
        
        private string typeField;
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private bool readonlyField;
        
        private bool readonlyFieldSpecified;
        
        private System.DateTime valueField;
        
        public DateTimeType() {
            this.typeField = "DateTime";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified {
            get {
                return this.mandatoryFieldSpecified;
            }
            set {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readonlySpecified {
            get {
                return this.readonlyFieldSpecified;
            }
            set {
                this.readonlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class StructureType {
        
        private string typeField;
        
        public StructureType() {
            this.typeField = "Structure";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceType {
        
        private request_changeInstanceTypeHeader headerField;
        
        private request_changeInstanceTypeDescriptionstructure descriptionstructureField;
        
        private request_changeInstanceTypeMiddle middleField;
        
        private request_changeInstanceTypeClose closeField;
        
        private request_changeInstanceTypeClosureComment closureCommentField;
        
        private AttachmentType[] attachmentsField;
        
        private string queryField;
        
        private string uniquequeryField;
        
        private string recordidField;
        
        private long updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        /// <remarks/>
        public request_changeInstanceTypeHeader header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description.structure")]
        public request_changeInstanceTypeDescriptionstructure descriptionstructure {
            get {
                return this.descriptionstructureField;
            }
            set {
                this.descriptionstructureField = value;
            }
        }
        
        /// <remarks/>
        public request_changeInstanceTypeMiddle middle {
            get {
                return this.middleField;
            }
            set {
                this.middleField = value;
            }
        }
        
        /// <remarks/>
        public request_changeInstanceTypeClose close {
            get {
                return this.closeField;
            }
            set {
                this.closeField = value;
            }
        }
        
        /// <remarks/>
        public request_changeInstanceTypeClosureComment ClosureComment {
            get {
                return this.closureCommentField;
            }
            set {
                this.closureCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attachment", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public AttachmentType[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uniquequery {
            get {
                return this.uniquequeryField;
            }
            set {
                this.uniquequeryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string recordid {
            get {
                return this.recordidField;
            }
            set {
                this.recordidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeHeader : StructureType {
        
        private StringType changeNumberField;
        
        private DateTimeType requestedDateField;
        
        private DateTimeType plannedStartField;
        
        private DateTimeType plannedEndField;
        
        private StringType phaseField;
        
        private DateTimeType updateTimeField;
        
        private DateTimeType openTimeField;
        
        private StringType titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeType RequestedDate {
            get {
                return this.requestedDateField;
            }
            set {
                this.requestedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeType PlannedStart {
            get {
                return this.plannedStartField;
            }
            set {
                this.plannedStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeType PlannedEnd {
            get {
                return this.plannedEndField;
            }
            set {
                this.plannedEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType Phase {
            get {
                return this.phaseField;
            }
            set {
                this.phaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeType UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeType OpenTime {
            get {
                return this.openTimeField;
            }
            set {
                this.openTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StringType Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeDescriptionstructure : StructureType {
        
        private request_changeInstanceTypeDescriptionstructureDescription descriptionField;
        
        /// <remarks/>
        public request_changeInstanceTypeDescriptionstructureDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeDescriptionstructureDescription : ArrayType {
        
        private StringType[] descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public StringType[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeMiddle : StructureType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeClose : StructureType {
        
        private DecimalType closureCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DecimalType ClosureCode {
            get {
                return this.closureCodeField;
            }
            set {
                this.closureCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class request_changeInstanceTypeClosureComment : ArrayType {
        
        private StringType[] closureCommentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClosureComment")]
        public StringType[] ClosureComment {
            get {
                return this.closureCommentField;
            }
            set {
                this.closureCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public partial class MessageType : StringType {
        
        private int severityField;
        
        private bool severityFieldSpecified;
        
        private string moduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeResponse {
        
        private request_changeModelType modelField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        public request_changeModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.hp.com/SM/7/Common")]
    public enum StatusType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeKeysListRequest {
        
        private request_changeModelType modelField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        public Retrieverequest_changeKeysListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        public request_changeModelType model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeKeysListResponse {
        
        private request_changeKeysType[] keysField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys")]
        public request_changeKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeListRequest {
        
        private request_changeKeysType[] keysField;
        
        private bool attachmentInfoField;
        
        private bool attachmentInfoFieldSpecified;
        
        private bool attachmentDataField;
        
        private bool attachmentDataFieldSpecified;
        
        private bool ignoreEmptyElementsField;
        
        private bool updatecounterField;
        
        private bool updatecounterFieldSpecified;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        private long attachmentTypeField;
        
        private bool attachmentTypeFieldSpecified;
        
        public Retrieverequest_changeListRequest() {
            this.ignoreEmptyElementsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys")]
        public request_changeKeysType[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentInfo {
            get {
                return this.attachmentInfoField;
            }
            set {
                this.attachmentInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentInfoSpecified {
            get {
                return this.attachmentInfoFieldSpecified;
            }
            set {
                this.attachmentInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool attachmentData {
            get {
                return this.attachmentDataField;
            }
            set {
                this.attachmentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentDataSpecified {
            get {
                return this.attachmentDataFieldSpecified;
            }
            set {
                this.attachmentDataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ignoreEmptyElements {
            get {
                return this.ignoreEmptyElementsField;
            }
            set {
                this.ignoreEmptyElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updatecounter {
            get {
                return this.updatecounterField;
            }
            set {
                this.updatecounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatecounterSpecified {
            get {
                return this.updatecounterFieldSpecified;
            }
            set {
                this.updatecounterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeSpecified {
            get {
                return this.attachmentTypeFieldSpecified;
            }
            set {
                this.attachmentTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.hp.com/SM/7")]
    public partial class Retrieverequest_changeListResponse {
        
        private request_changeInstanceType[] instanceField;
        
        private MessageType[] messagesField;
        
        private StatusType statusField;
        
        private string messageField;
        
        private System.DateTime schemaRevisionDateField;
        
        private int schemaRevisionLevelField;
        
        private decimal returnCodeField;
        
        private bool returnCodeFieldSpecified;
        
        private string queryField;
        
        private string handleField;
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private bool moreField;
        
        private bool moreFieldSpecified;
        
        private long startField;
        
        private bool startFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instance")]
        public request_changeInstanceType[] instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("message", Namespace="http://schemas.hp.com/SM/7/Common", IsNullable=false)]
        public MessageType[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime schemaRevisionDate {
            get {
                return this.schemaRevisionDateField;
            }
            set {
                this.schemaRevisionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int schemaRevisionLevel {
            get {
                return this.schemaRevisionLevelField;
            }
            set {
                this.schemaRevisionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnCodeSpecified {
            get {
                return this.returnCodeFieldSpecified;
            }
            set {
                this.returnCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool more {
            get {
                return this.moreField;
            }
            set {
                this.moreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreSpecified {
            get {
                return this.moreFieldSpecified;
            }
            set {
                this.moreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void Retrieverequest_changeCompletedEventHandler(object sender, Retrieverequest_changeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Retrieverequest_changeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Retrieverequest_changeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retrieverequest_changeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retrieverequest_changeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void Retrieverequest_changeKeysListCompletedEventHandler(object sender, Retrieverequest_changeKeysListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Retrieverequest_changeKeysListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Retrieverequest_changeKeysListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retrieverequest_changeKeysListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retrieverequest_changeKeysListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void Retrieverequest_changeListCompletedEventHandler(object sender, Retrieverequest_changeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Retrieverequest_changeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Retrieverequest_changeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retrieverequest_changeListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retrieverequest_changeListResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591